export {
  MATCH3_BOOSTERS,
  MATCH3_COLORS,
  MATCH3_COLUMNS,
  MATCH3_LEVEL_COUNT,
  MATCH3_LEVELS,
  MATCH3_ROWS,
  MATCH3_RULES_VERSION,
  MATCH3_SPECIALS,
  areMatch3Neighbors,
  cloneMatch3Board,
  cloneMatch3State,
  createMatch3State,
  findMatch3Runs,
  findValidMatch3Moves,
  getMatch3LevelDefinition,
  isMatch3Coordinate,
  match3BoardFingerprint,
  match3Hint,
  match3MatchedCoordinates,
  match3ObjectivesComplete,
  nextMatch3Random,
  tryMatch3Swap,
  useMatch3Booster,
} from '../../shared/runtime/match3-core.mjs';

export type {
  Match3ActionResult,
  Match3Board,
  Match3Booster,
  Match3Boosters,
  Match3Cell,
  Match3ClearedTile,
  Match3Color,
  Match3Coordinate,
  Match3CreatedSpecial,
  Match3Goals,
  Match3LevelDefinition,
  Match3Move,
  Match3Progress,
  Match3ResolutionStep,
  Match3Run,
  Match3Special,
  Match3State,
  Match3Status,
  Match3Tile,
} from '../../shared/runtime/match3-core.mjs';
